language: rust

addons:
  mariadb: '10.0'

rust:
  - nightly

os:
  - linux

dist: trusty

install: true

script:
  - cd backend
  - sudo mysql -uroot -proot < database_init.sql
  - mysql -uacmuser -presumca acm_manager < migrations/2019-12-11-053044_users/up.sql
  - cargo test